- name: tomcat installation on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: adding user group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: adding user
      ansible.builtin.user:
        name: tomcat
        create_home: yes
        home: /opt/tomcat
        group: tomcat
        shell: /bin/false
        state: present
    - name: downloding tomcat package
      ansible.builtin.unarchive:
        src: https://downloads.apache.org/tomcat/tomcat-10/v10.1.24/bin/apache-tomcat-10.1.24.tar.gz
        remote_src: yes
        dest: /opt/tomcat
    - name: creating sybmolic link
      ansible.builtin.file:
        src: /opt/tomcat/apache-tomcat-10.1.24
        dest: /opt/tomcat/latest
        state: link
    - name: change file permissions
      ansible.builtin.file:
        dest: /opt/tomcat
        recurse: true
        owner: tomcat
        group: tomcat
        state: directory
    - name: excecution of tomcat
      ansible.builtin.command: sudo sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'
    - name: copy systemd file
      ansible.builtin.copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
        owner: tomcat
        group: tomcat
    - name: reload daemon and start tomcat
      ansible.builtin.systemd:
        name: tomcat.service
        daemon_reload: yes
        enabled: yes
        state: started
    - name: tomcat user file
      ansible.builtin.copy:
        src: tomcat.service
        dest: /opt/tomcat/latest/tomcat-users.xml
        owner: tomcat
        group: tomcat
    - name: context file copy
      ansible.builtin.copy:
        src: context.xml
        dest: /opt/tomcat/latest/webapps/manager/META-INF/context.xml
        owner: tomcat
        group: tomcat
    - name: copy the host manager app context file
      ansible.builtin.copy:
        src: hostmanager-context.xml
        dest: /opt/tomcat/latest/webapps/host-manager/META-INF/context.xml
        owner: tomcat
        group: tomcat
    - name: restart tomcat
      ansible.builtin.systemd:
        name: tomcat.service
        state: restarted