--- 
- name: tomcat installation on ubuntu 
  hosts: all
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: "true"
        state: present
    - name: adding user group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: adding user
      ansible.builtin.user:
        name: tomcat
        create_home: yes
        home: /opt/tomcat
        group: tomcat
        shell: /bin/false  
    - name: downloding tomcat package
      ansible.builtin.unarchive:
        src: https://downloads.apache.org/tomcat/tomcat-10/v10.1.24/bin/apache-tomcat-10.1.24.tar.gz
        remote_src: yes
        dest: /opt/tomcat
    - name: sybmolic link creation
      ansible.builtin.file:
        src: /opt/tomcat/apache-tomcat-10.1.24
        dest: /opt/tomcat/latest
        state: directory
    - name: change of file permissions
      ansible.builtin.file:
        path: /opt/tomcat/latest
        recurse: yes
        dest: /opt/tomcat/latest
        group: tomcat
        owner: tomcat
        state: directory
    - name: excecution of tomcat code 
      ansible.builtin.command: sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'
   