- name: tomcat installation on ubuntu
  hosts: appservers
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.package:
        name: "{{java_name}}"
        update_cache: yes
        state: present
    - name: adding user group
      ansible.builtin.group:
        name: "{{group_name}}"
        state: present
    - name: adding user
      ansible.builtin.user:
        name: tomcat
        create_home: yes
        home: "{{user_home}}"
        group: "{{user_name}}"
        shell: "{{shell}}"
        state: present
    - name: get tomcat stats
      ansible.builtin.stat:
        path: "{{ user_home }}/latest/bin/startup.sh"
      register: tomcat_startup
    - name: downloding tomcat package
      ansible.builtin.unarchive:
        src: https://downloads.apache.org/tomcat/tomcat-{{tomcat_maj_v}}/v{{tomcat_v}}/bin/apache-tomcat-{{tomcat_v}}.tar.gz
        remote_src: yes
        dest: "{{user_home}}"
      when: not tomcat_startup.stat.exists
    - name: creating sybmolic link
      ansible.builtin.file:
        src: "{{user_home}}/apache-tomcat-{{tomcat_v}}"
        dest: "{{user_home}}/latest"
        state: link
      notify:
        - change file permissions
        - excecution of tomcat
    - name: copy systemd file ubuntu
      ansible.builtin.copy:
        src: ubuntu.tomcat.service
        dest: /etc/systemd/system/tomcat.service
        owner: "{{user_name}}"
        group: "{{group_name}}"
      when: ansible_facts['distribution'] == "Ubuntu"
      notify:
        - enable and reload tomcat
    - name: copy systemd file on Centos
      ansible.builtin.copy:
        src: centos.tomcat.service
        dest: /etc/systemd/system/tomcat.service
        owner: "{{user_name}}"
        group: "{{group_name}}"
      when: ansible_facts['distribution'] == "CentOS"
      notify:
        - enable and reload tomcat
    - name: tomcat user file
      ansible.builtin.copy:
        src: tomcat.service
        dest: /opt/tomcat/latest/conf/tomcat-users.xml
        owner: "{{user_name}}"
        group: "{{group_name}}"
      notify:
        - restart tomcat
    - name: context file copy
      ansible.builtin.copy:
        src: context.xml
        dest: "{{user_home}}/latest/webapps/manager/META-INF/context.xml"
        owner: "{{user_name}}"
        group: "{{group_name}}"
      notify:
        - restart tomcat
    - name: copy the host manager app context file
      ansible.builtin.copy:
        src: hostmanager-context.xml
        dest: "{{user_home}}/latest/webapps/host-manager/META-INF/context.xml"
        owner: "{{user_name}}"
        group: "{{group_name}}"
      notify:
        - restart tomcat
  handlers:
    - name: restart tomcat
      ansible.builtin.systemd:
        name: tomcat.service
        daemon_reload: yes
        enabled: yes
        state: started
    - name: excecution of tomcat
      ansible.builtin.command: sudo sh -c 'chmod +x {{user_home}}/latest/bin/*.sh'
      when: not tomcat_startup.stat.exists
    - name: change file permissions
      ansible.builtin.file:
        dest: "{{user_home}}"
        recurse: true
        owner: "{{user_name}}"
        group: "{{group_name}}"
        state: directory
    - name: enable and reload tomcat
      ansible.builtin.systemd:
        name: tomcat.service
        state: restarted