- name: tomcat installation on ubuntu
  hosts: appservers
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: adding user group
      ansible.builtin.group:
        name: "{{group_name}}"
        state: present
    - name: adding user
      ansible.builtin.user:
        name: tomcat
        create_home: yes
        home: "{{user_home}}"
        group: "{{user_name}}"
        shell: "{{shell}}"
        state: present
    - name: downloding tomcat package
      ansible.builtin.unarchive:
        src: https://downloads.apache.org/tomcat/tomcat-{{tomcat_maj_v}}/v{{tomcat_v}}/bin/apache-tomcat-{{tomcat_v}}.tar.gz
        remote_src: yes
        dest: "{{user_home}}"
    - name: creating sybmolic link
      ansible.builtin.file:
        src: "{{user_home}}/apache-tomcat-{{tomcat_v}}"
        dest: "{{user_home}}/latest"
        state: link
    - name: change file permissions
      ansible.builtin.file:
        dest: "{{user_home}}"
        recurse: true
        owner: "{{user_name}}"
        group: "{{group_name}}"
        state: directory
    - name: excecution of tomcat
      ansible.builtin.command: sudo sh -c 'chmod +x {{user_home}}/latest/bin/*.sh'
    - name: copy systemd file
      ansible.builtin.copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
        owner: "{{user_name}}"
        group: "{{group_name}}"
    - name: reload daemon and start tomcat
      ansible.builtin.systemd:
        name: tomcat.service
        daemon_reload: yes
        enabled: yes
        state: started
    - name: tomcat user file
      ansible.builtin.copy:
        src: tomcat.service
        dest: /opt/tomcat/latest/conf/tomcat-users.xml
        owner: "{{user_name}}"
        group: "{{group_name}}"
    - name: context file copy
      ansible.builtin.copy:
        src: context.xml
        dest: "{{user_hoem}}/latest/webapps/manager/META-INF/context.xml"
        owner: "{{user_name}}"
        group: "{{group_name}}"
    - name: copy the host manager app context file
      ansible.builtin.copy:
        src: hostmanager-context.xml
        dest: "{{user_home}}/latest/webapps/host-manager/META-INF/context.xml"
        owner: "{{user_name}}"
        group: "{{group_name}}"
    - name: restart tomcat
      ansible.builtin.systemd:
        name: tomcat.service
        state: restarted